import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SideBar } from "@/app/components/side-bar/sideBar";
import { Menu } from "@/app/components/menu-bar/menu";
import { SearchProvider } from "@/lib/searchQueryConext";
import { Main } from "next/document";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchProvider>
          <main className={"h-[100svh] w-[100svw]"}>
            <Menu />
            <div className={"relative flex flex-row"}>
              <SideBar />
              <section className={"relative flex flex-grow"}>
                {children}
              </section>
            </div>
          </main>
        </SearchProvider>
      </body>
    </html>
  );
}
